- name: Install pip
  apt: name=python3-pip

- name: Install virtualenv
  pip:
    name=virtualenv
    executable=pip3

- name: Check if virtualenv already exists
  stat: path="/{{ user }}/{{ project_name }}/"
  register: venv_dir

- name: Create virtualenv for bee-server
  shell: "virtualenv /{{ user }}/{{ project_name}} --python=python3"
  when: venv_dir.stat.isdir is not defined
  become: yes
  become_user: "{{ user }}"
