- name: "Create {{ group }} group"
  group: name="{{ group }}"

- name: "Create {{ user }} user"
  user:
    name="{{ user }}"
    state=present
    home="/{{ user }}"
    group="{{ group }}"

- name: "Create {{ user }} directories"
  file:
    path="/{{ user }}/{{ item }}"
    state=directory
    owner="{{ user }}"
    group="{{ group }}"
    mode=0740
  with_items:
    - '.ssh'
