# Generated by Django 2.0.3 on 2018-04-06 20:13

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import maasaic.apps.content.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_type', models.CharField(choices=[('IFRAME', 'IFRAME'), ('IMAGE', 'IMAGE'), ('TEXT', 'TEXT')], max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('h', models.PositiveIntegerField(help_text='Number of cells')),
                ('w', models.PositiveIntegerField(help_text='Number of cells')),
                ('x', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)], help_text='Number of cells')),
                ('y', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32)], help_text='Number of cells')),
                ('content', models.TextField(blank=True, null=True)),
                ('css', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('padding', models.CharField(default='20px', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('EDIT', 'EDIT'), ('LIVE', 'LIVE')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('page_width', models.PositiveIntegerField(blank=True, default=1000, help_text='In pixels', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_page', to='content.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('is_visible', models.BooleanField(default=True)),
                ('n_columns', models.PositiveIntegerField(default=5, help_text='Measured in cells', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('n_rows', models.PositiveIntegerField(default=1, help_text='Measured in cells', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)])),
                ('cell_height', models.PositiveIntegerField(choices=[(100, 'HEIGHT_100'), (150, 'HEIGHT_150'), (200, 'HEIGHT_200'), (50, 'HEIGHT_50')], help_text='In pixels')),
                ('css', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Page')),
                ('target_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False)),
                ('private_domain', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('subdomain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', maasaic.apps.content.models.LanguageField(choices=[('EN', 'EN'), ('ES', 'ES')], max_length=255)),
                ('favicon', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=maasaic.apps.content.models.favicon_path)),
                ('favicon_cropping', image_cropping.fields.ImageRatioField('favicon', '128x128', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='favicon cropping')),
                ('page_width', models.PositiveIntegerField(default=1000, help_text='In pixels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Website'),
        ),
        migrations.AddField(
            model_name='cell',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Section'),
        ),
        migrations.AddField(
            model_name='cell',
            name='target_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Cell'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('page', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('website', 'path', 'mode')},
        ),
    ]
