# Generated by Django 2.0.3 on 2018-03-21 13:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import maasaic.apps.content.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('TEXT', 'TEXT'), ('VIDEO', 'VIDEO')], max_length=255)),
                ('background', models.TextField(blank=True, null=True)),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('css', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CellImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropping', models.CharField(max_length=255)),
                ('alt_text', models.CharField(max_length=255)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Cell')),
            ],
        ),
        migrations.CreateModel(
            name='CellPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Cell')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('alt_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_status', maasaic.apps.content.models.PublicationStatusField(choices=[('DELETED', 'DELETED'), ('PUBLISHED', 'PUBLISHED'), ('UN_PUBLISHED', 'UN_PUBLISHED')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_status', maasaic.apps.content.models.PublicationStatusField(choices=[('DELETED', 'DELETED'), ('PUBLISHED', 'PUBLISHED'), ('UN_PUBLISHED', 'UN_PUBLISHED')], max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_status', maasaic.apps.content.models.PublicationStatusField(choices=[('DELETED', 'DELETED'), ('PUBLISHED', 'PUBLISHED'), ('UN_PUBLISHED', 'UN_PUBLISHED')], max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', maasaic.apps.content.models.LanguageField(choices=[('English', 'EN'), ('Spanish', 'ES')], max_length=255)),
                ('favicon', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=maasaic.apps.content.models.favicon_path)),
                ('favicon_cropping', image_cropping.fields.ImageRatioField('favicon', '128x128', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='favicon cropping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Website'),
        ),
        migrations.AddField(
            model_name='image',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Website'),
        ),
        migrations.AddField(
            model_name='cellposition',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Row'),
        ),
        migrations.AddField(
            model_name='cellimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Image'),
        ),
        migrations.AlterUniqueTogether(
            name='row',
            unique_together={('page', 'order')},
        ),
    ]
