# Generated by Django 2.0.3 on 2018-03-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Row',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='cellposition',
            old_name='row',
            new_name='section',
        ),
    ]
