# Generated by Django 2.0.4 on 2018-05-03 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Website'),
        ),
        migrations.AddField(
            model_name='sitedefaultprop',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Website'),
        ),
        migrations.AddField(
            model_name='section',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Page'),
        ),
        migrations.AddField(
            model_name='pagefont',
            name='font',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Font'),
        ),
        migrations.AddField(
            model_name='pagefont',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='target_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_page', to='content.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Website'),
        ),
        migrations.AddField(
            model_name='cellimage',
            name='cell',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.Cell'),
        ),
        migrations.AddField(
            model_name='cellimage',
            name='uploaded_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.UploadedImage'),
        ),
        migrations.AddField(
            model_name='cell',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='sitedefaultprop',
            unique_together={('site', 'scope', 'prop')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('website', 'path', 'mode')},
        ),
    ]
