# Generated by Django 2.0.3 on 2018-04-07 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180407_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='cell_height',
            field=models.PositiveIntegerField(choices=[(100, '100_px'), (110, '110_px'), (120, '120_px'), (130, '130_px'), (140, '140_px'), (150, '150_px'), (160, '160_px'), (180, '180_px'), (190, '190_px'), (200, '200_px'), (210, '210_px'), (220, '220_px'), (230, '230_px'), (240, '240_px'), (250, '250_px'), (30, '30_px'), (40, '40_px'), (50, '50_px'), (60, '60_px'), (70, '70_px'), (80, '80_px'), (90, '90_px')]),
        ),
        migrations.AlterField(
            model_name='section',
            name='html_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='n_columns',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='n_rows',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='yo', max_length=255),
            preserve_default=False,
        ),
    ]
