# Generated by Django 2.0.3 on 2018-03-27 13:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_page_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='css',
        ),
        migrations.AddField(
            model_name='section',
            name='css',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
