# Generated by Django 2.0.3 on 2018-04-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180407_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='cell',
            name='padding',
        ),
    ]
