# Generated by Django 2.0.3 on 2018-03-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180327_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='padding',
            field=models.CharField(default='20px', max_length=255),
        ),
    ]
