# Generated by Django 2.0.3 on 2018-03-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_cell_padding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='height',
            new_name='h',
        ),
        migrations.RenameField(
            model_name='cell',
            old_name='width',
            new_name='w',
        ),
    ]
