# Generated by Django 2.0.3 on 2018-04-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20180411_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
