# Generated by Django 2.0.3 on 2018-04-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_cell_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ('order',)},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
    ]
