# Generated by Django 2.0.3 on 2018-03-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20180327_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
