# Generated by Django 2.0.3 on 2018-03-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_cell_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='pub_status',
        ),
        migrations.RemoveField(
            model_name='website',
            name='pub_status',
        ),
        migrations.AddField(
            model_name='page',
            name='mode',
            field=models.CharField(choices=[('EDIT', 'EDIT'), ('LIVE', 'LIVE')], default='EDIT', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_type',
            field=models.CharField(choices=[('IFRAME', 'IFRAME'), ('IMAGE', 'IMAGE'), ('TEXT', 'TEXT')], max_length=255),
        ),
        migrations.RemoveField(
            model_name='page',
            name='pub_status',
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('parent_page', 'slug', 'mode')},
        ),
    ]
