# Generated by Django 2.0.3 on 2018-04-14 16:01

from django.db import migrations, models
import django.db.models.deletion
import maasaic.apps.content.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20180413_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=maasaic.apps.content.models.image_path)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('size', models.IntegerField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Website')),
            ],
        ),
    ]
