# Generated by Django 2.0.3 on 2018-04-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
