# Generated by Django 2.0.3 on 2018-04-15 07:17

from django.db import migrations, models
import django.utils.timezone
import maasaic.apps.content.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20180414_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='target_cell',
        ),
        migrations.RemoveField(
            model_name='section',
            name='target_section',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to=maasaic.apps.content.models.image_path, width_field='width'),
        ),
    ]
