# Generated by Django 2.0.4 on 2018-04-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20180415_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_width',
        ),
        migrations.RemoveField(
            model_name='section',
            name='cell_height',
        ),
        migrations.AddField(
            model_name='page',
            name='width',
            field=models.PositiveIntegerField(choices=[(1000, '1000_px'), (1200, '1200_px'), (600, '600_px'), (800, '800_px')], default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='page_width',
            field=models.PositiveIntegerField(choices=[(1000, '1000_px'), (1200, '1200_px'), (600, '600_px'), (800, '800_px')]),
        ),
    ]
