# Generated by Django 2.0.4 on 2018-04-22 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_cellpropattr_sectiondefaultprop'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDefaultProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('CELL', 'CELL'), ('SECTION', 'SECTION')], max_length=255)),
                ('prop', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Page')),
            ],
        ),
        migrations.RemoveField(
            model_name='cellpropattr',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sectiondefaultprop',
            name='site',
        ),
        migrations.DeleteModel(
            name='CellPropAttr',
        ),
        migrations.DeleteModel(
            name='SectionDefaultProp',
        ),
    ]
