# Generated by Django 2.0.4 on 2018-04-22 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20180422_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedefaultprop',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Website'),
        ),
    ]
