# Generated by Django 2.0.4 on 2018-05-01 07:36

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20180422_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('cropping', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Cell')),
                ('uploaded_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.UploadedImage')),
            ],
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='page_width',
            field=models.PositiveIntegerField(choices=[(1000, '1000_px'), (1200, '1200_px'), (600, '600_px'), (800, '800_px')], default=1000),
        ),
        migrations.AlterField(
            model_name='website',
            name='subdomain',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterUniqueTogether(
            name='sitedefaultprop',
            unique_together={('site', 'scope', 'prop')},
        ),
    ]
