# Generated by Django 2.0.4 on 2018-05-03 01:04

from django.db import migrations, models
import django.db.models.deletion
import maasaic.apps.content.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20180501_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('css_name', models.CharField(max_length=255)),
                ('default', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='cellimage',
            name='cell',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.Cell'),
        ),
        migrations.AlterField(
            model_name='cellimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=maasaic.apps.content.models.image_cell_path),
        ),
    ]
