# Generated by Django 2.0.4 on 2018-05-03 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20180503_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlefont',
            name='css_name',
        ),
    ]
