# Generated by Django 2.0.4 on 2018-05-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_remove_googlefont_css_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlefont',
            name='url',
        ),
    ]
