# Generated by Django 2.0.4 on 2018-05-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_googlefont_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.CharField(max_length=255)),
                ('source', models.CharField(default='NATIVE', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='GoogleFont',
        ),
    ]
