# Generated by Django 2.0.4 on 2018-05-03 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20180503_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='font',
            name='default',
            field=models.CharField(default='sans-serif', max_length=255),
        ),
        migrations.AlterField(
            model_name='font',
            name='source',
            field=models.CharField(default='GOOGLE', max_length=255),
        ),
        migrations.AddField(
            model_name='pagefont',
            name='font',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Font'),
        ),
        migrations.AddField(
            model_name='pagefont',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Page'),
        ),
    ]
